/*
 * Stocks
 * <h3>Authentication</h3>                     You need to authenticate to use this API.                     To authenticate click on the \"Authorize\" button and do one of the following steps.<br />                     1. Send your API key in the headers of the request by typing \"Bearer my-key\" on the Bearer authorization scheme.<br />                     2. Send your API key on the \"ApiKey\" query string parameter. To do this type your API key in the Query String authorization scheme.<br />                     Both methods are equally valid. We offer both options so that you can use the method that is easier to use in your application.<br />                     <br />                     <h3>API limits</h3>                     Your API key may be subject to daily/hourly limits. To know how much requests you have left look at the following headers in the response.<br />                     1. <strong>x-ratelimit-limit</strong> - The total number of requests that you are allowed to make in a given period (hour/day)                       2. <strong>x-ratelimit-remaining</strong> - The number of remaining requests that you can perform in the current period.<br />                     3. <strong>x-ratelimit-reset</strong> - The number of seconds until the current period resets.<br />                     <br />                     <h3>Suggestions</h3>                     You don't need to implement the whole API by hand in your programming language of choice.<br />                     Since this API has an OpenAPI specification you can use                      <a href=\"https://github.com/swagger-api/swagger-codegen\" target=\"_blank\">Swagger Generator</a>                      to automatically generate client stubs for more than 30 programming languages.                     <br />                     <br />                     You don't have an API key? <a href=\"https://www.equibles.com/api/pricing\" target=\"_blank\">Get one for free here.</a>
 *
 * OpenAPI spec version: v1
 * Contact: equibles@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.equibles.stocks.models;

import java.util.Objects;
import java.util.Arrays;
import com.equibles.stocks.models.AssetType;
import com.equibles.stocks.models.Exchange;
import com.equibles.stocks.models.Image;
import com.equibles.stocks.models.Industry;
import com.equibles.stocks.models.Officer;
import com.equibles.stocks.models.Price;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;
/**
 * CommonStock
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-01-28T01:43:07.282Z[Europe/Lisbon]")
public class CommonStock {
  @SerializedName("logo")
  private Image logo = null;

  @SerializedName("address")
  private String address = null;

  @SerializedName("cik")
  private String cik = null;

  @SerializedName("locale")
  private String locale = null;

  @SerializedName("marketCap")
  private Long marketCap = null;

  @SerializedName("sharesOutstandingLast")
  private Long sharesOutstandingLast = null;

  @SerializedName("phoneNumber")
  private String phoneNumber = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("employees")
  private Long employees = null;

  @SerializedName("delisted")
  private Boolean delisted = null;

  @SerializedName("listDate")
  private OffsetDateTime listDate = null;

  @SerializedName("website")
  private String website = null;

  @SerializedName("industry")
  private Industry industry = null;

  @SerializedName("officers")
  private List<Officer> officers = null;

  @SerializedName("ticker")
  private String ticker = null;

  @SerializedName("fullTicker")
  private String fullTicker = null;

  @SerializedName("assetType")
  private AssetType assetType = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("exchange")
  private Exchange exchange = null;

  @SerializedName("lastPrice")
  private Price lastPrice = null;

  public CommonStock logo(Image logo) {
    this.logo = logo;
    return this;
  }

   /**
   * Get logo
   * @return logo
  **/
  @Schema(description = "")
  public Image getLogo() {
    return logo;
  }

  public void setLogo(Image logo) {
    this.logo = logo;
  }

  public CommonStock address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @Schema(description = "")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public CommonStock cik(String cik) {
    this.cik = cik;
    return this;
  }

   /**
   * Get cik
   * @return cik
  **/
  @Schema(description = "")
  public String getCik() {
    return cik;
  }

  public void setCik(String cik) {
    this.cik = cik;
  }

  public CommonStock locale(String locale) {
    this.locale = locale;
    return this;
  }

   /**
   * Get locale
   * @return locale
  **/
  @Schema(description = "")
  public String getLocale() {
    return locale;
  }

  public void setLocale(String locale) {
    this.locale = locale;
  }

  public CommonStock marketCap(Long marketCap) {
    this.marketCap = marketCap;
    return this;
  }

   /**
   * Get marketCap
   * @return marketCap
  **/
  @Schema(description = "")
  public Long getMarketCap() {
    return marketCap;
  }

  public void setMarketCap(Long marketCap) {
    this.marketCap = marketCap;
  }

  public CommonStock sharesOutstandingLast(Long sharesOutstandingLast) {
    this.sharesOutstandingLast = sharesOutstandingLast;
    return this;
  }

   /**
   * Get sharesOutstandingLast
   * @return sharesOutstandingLast
  **/
  @Schema(description = "")
  public Long getSharesOutstandingLast() {
    return sharesOutstandingLast;
  }

  public void setSharesOutstandingLast(Long sharesOutstandingLast) {
    this.sharesOutstandingLast = sharesOutstandingLast;
  }

  public CommonStock phoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

   /**
   * Get phoneNumber
   * @return phoneNumber
  **/
  @Schema(description = "")
  public String getPhoneNumber() {
    return phoneNumber;
  }

  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  public CommonStock description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CommonStock employees(Long employees) {
    this.employees = employees;
    return this;
  }

   /**
   * Get employees
   * @return employees
  **/
  @Schema(description = "")
  public Long getEmployees() {
    return employees;
  }

  public void setEmployees(Long employees) {
    this.employees = employees;
  }

  public CommonStock delisted(Boolean delisted) {
    this.delisted = delisted;
    return this;
  }

   /**
   * Get delisted
   * @return delisted
  **/
  @Schema(description = "")
  public Boolean isDelisted() {
    return delisted;
  }

  public void setDelisted(Boolean delisted) {
    this.delisted = delisted;
  }

  public CommonStock listDate(OffsetDateTime listDate) {
    this.listDate = listDate;
    return this;
  }

   /**
   * Get listDate
   * @return listDate
  **/
  @Schema(description = "")
  public OffsetDateTime getListDate() {
    return listDate;
  }

  public void setListDate(OffsetDateTime listDate) {
    this.listDate = listDate;
  }

  public CommonStock website(String website) {
    this.website = website;
    return this;
  }

   /**
   * Get website
   * @return website
  **/
  @Schema(description = "")
  public String getWebsite() {
    return website;
  }

  public void setWebsite(String website) {
    this.website = website;
  }

  public CommonStock industry(Industry industry) {
    this.industry = industry;
    return this;
  }

   /**
   * Get industry
   * @return industry
  **/
  @Schema(description = "")
  public Industry getIndustry() {
    return industry;
  }

  public void setIndustry(Industry industry) {
    this.industry = industry;
  }

  public CommonStock officers(List<Officer> officers) {
    this.officers = officers;
    return this;
  }

  public CommonStock addOfficersItem(Officer officersItem) {
    if (this.officers == null) {
      this.officers = new ArrayList<Officer>();
    }
    this.officers.add(officersItem);
    return this;
  }

   /**
   * Get officers
   * @return officers
  **/
  @Schema(description = "")
  public List<Officer> getOfficers() {
    return officers;
  }

  public void setOfficers(List<Officer> officers) {
    this.officers = officers;
  }

  public CommonStock ticker(String ticker) {
    this.ticker = ticker;
    return this;
  }

   /**
   * Get ticker
   * @return ticker
  **/
  @Schema(description = "")
  public String getTicker() {
    return ticker;
  }

  public void setTicker(String ticker) {
    this.ticker = ticker;
  }

  public CommonStock fullTicker(String fullTicker) {
    this.fullTicker = fullTicker;
    return this;
  }

   /**
   * Get fullTicker
   * @return fullTicker
  **/
  @Schema(description = "")
  public String getFullTicker() {
    return fullTicker;
  }

  public void setFullTicker(String fullTicker) {
    this.fullTicker = fullTicker;
  }

  public CommonStock assetType(AssetType assetType) {
    this.assetType = assetType;
    return this;
  }

   /**
   * Get assetType
   * @return assetType
  **/
  @Schema(description = "")
  public AssetType getAssetType() {
    return assetType;
  }

  public void setAssetType(AssetType assetType) {
    this.assetType = assetType;
  }

  public CommonStock name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CommonStock exchange(Exchange exchange) {
    this.exchange = exchange;
    return this;
  }

   /**
   * Get exchange
   * @return exchange
  **/
  @Schema(description = "")
  public Exchange getExchange() {
    return exchange;
  }

  public void setExchange(Exchange exchange) {
    this.exchange = exchange;
  }

  public CommonStock lastPrice(Price lastPrice) {
    this.lastPrice = lastPrice;
    return this;
  }

   /**
   * Get lastPrice
   * @return lastPrice
  **/
  @Schema(description = "")
  public Price getLastPrice() {
    return lastPrice;
  }

  public void setLastPrice(Price lastPrice) {
    this.lastPrice = lastPrice;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommonStock commonStock = (CommonStock) o;
    return Objects.equals(this.logo, commonStock.logo) &&
        Objects.equals(this.address, commonStock.address) &&
        Objects.equals(this.cik, commonStock.cik) &&
        Objects.equals(this.locale, commonStock.locale) &&
        Objects.equals(this.marketCap, commonStock.marketCap) &&
        Objects.equals(this.sharesOutstandingLast, commonStock.sharesOutstandingLast) &&
        Objects.equals(this.phoneNumber, commonStock.phoneNumber) &&
        Objects.equals(this.description, commonStock.description) &&
        Objects.equals(this.employees, commonStock.employees) &&
        Objects.equals(this.delisted, commonStock.delisted) &&
        Objects.equals(this.listDate, commonStock.listDate) &&
        Objects.equals(this.website, commonStock.website) &&
        Objects.equals(this.industry, commonStock.industry) &&
        Objects.equals(this.officers, commonStock.officers) &&
        Objects.equals(this.ticker, commonStock.ticker) &&
        Objects.equals(this.fullTicker, commonStock.fullTicker) &&
        Objects.equals(this.assetType, commonStock.assetType) &&
        Objects.equals(this.name, commonStock.name) &&
        Objects.equals(this.exchange, commonStock.exchange) &&
        Objects.equals(this.lastPrice, commonStock.lastPrice);
  }

  @Override
  public int hashCode() {
    return Objects.hash(logo, address, cik, locale, marketCap, sharesOutstandingLast, phoneNumber, description, employees, delisted, listDate, website, industry, officers, ticker, fullTicker, assetType, name, exchange, lastPrice);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommonStock {\n");
    
    sb.append("    logo: ").append(toIndentedString(logo)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    cik: ").append(toIndentedString(cik)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    marketCap: ").append(toIndentedString(marketCap)).append("\n");
    sb.append("    sharesOutstandingLast: ").append(toIndentedString(sharesOutstandingLast)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    employees: ").append(toIndentedString(employees)).append("\n");
    sb.append("    delisted: ").append(toIndentedString(delisted)).append("\n");
    sb.append("    listDate: ").append(toIndentedString(listDate)).append("\n");
    sb.append("    website: ").append(toIndentedString(website)).append("\n");
    sb.append("    industry: ").append(toIndentedString(industry)).append("\n");
    sb.append("    officers: ").append(toIndentedString(officers)).append("\n");
    sb.append("    ticker: ").append(toIndentedString(ticker)).append("\n");
    sb.append("    fullTicker: ").append(toIndentedString(fullTicker)).append("\n");
    sb.append("    assetType: ").append(toIndentedString(assetType)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    exchange: ").append(toIndentedString(exchange)).append("\n");
    sb.append("    lastPrice: ").append(toIndentedString(lastPrice)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
