/*
 * Stocks
 * <h3>Authentication</h3>                     You need to authenticate to use this API.                     To authenticate click on the \"Authorize\" button and do one of the following steps.<br />                     1. Send your API key in the headers of the request by typing \"Bearer my-key\" on the Bearer authorization scheme.<br />                     2. Send your API key on the \"ApiKey\" query string parameter. To do this type your API key in the Query String authorization scheme.<br />                     Both methods are equally valid. We offer both options so that you can use the method that is easier to use in your application.<br />                     <br />                     <h3>API limits</h3>                     Your API key may be subject to daily/hourly limits. To know how much requests you have left look at the following headers in the response.<br />                     1. <strong>x-ratelimit-limit</strong> - The total number of requests that you are allowed to make in a given period (hour/day)                       2. <strong>x-ratelimit-remaining</strong> - The number of remaining requests that you can perform in the current period.<br />                     3. <strong>x-ratelimit-reset</strong> - The number of seconds until the current period resets.<br />                     <br />                     <h3>Suggestions</h3>                     You don't need to implement the whole API by hand in your programming language of choice.<br />                     Since this API has an OpenAPI specification you can use                      <a href=\"https://github.com/swagger-api/swagger-codegen\" target=\"_blank\">Swagger Generator</a>                      to automatically generate client stubs for more than 30 programming languages.                     <br />                     <br />                     You don't have an API key? <a href=\"https://www.equibles.com/api/pricing\" target=\"_blank\">Get one for free here.</a>
 *
 * OpenAPI spec version: v1
 * Contact: equibles@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.equibles.stocks.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;
/**
 * News
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-02-02T22:10:29.848Z[Europe/Lisbon]")
public class News {
  @SerializedName("title")
  private String title = null;

  @SerializedName("ampUrl")
  private String ampUrl = null;

  @SerializedName("articleUrl")
  private String articleUrl = null;

  @SerializedName("author")
  private String author = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("imageUrl")
  private String imageUrl = null;

  @SerializedName("keywords")
  private List<String> keywords = null;

  @SerializedName("financialAssets")
  private List<String> financialAssets = null;

  @SerializedName("publishedTime")
  private OffsetDateTime publishedTime = null;

  @SerializedName("publisherName")
  private String publisherName = null;

  public News title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @Schema(description = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public News ampUrl(String ampUrl) {
    this.ampUrl = ampUrl;
    return this;
  }

   /**
   * Get ampUrl
   * @return ampUrl
  **/
  @Schema(description = "")
  public String getAmpUrl() {
    return ampUrl;
  }

  public void setAmpUrl(String ampUrl) {
    this.ampUrl = ampUrl;
  }

  public News articleUrl(String articleUrl) {
    this.articleUrl = articleUrl;
    return this;
  }

   /**
   * Get articleUrl
   * @return articleUrl
  **/
  @Schema(description = "")
  public String getArticleUrl() {
    return articleUrl;
  }

  public void setArticleUrl(String articleUrl) {
    this.articleUrl = articleUrl;
  }

  public News author(String author) {
    this.author = author;
    return this;
  }

   /**
   * Get author
   * @return author
  **/
  @Schema(description = "")
  public String getAuthor() {
    return author;
  }

  public void setAuthor(String author) {
    this.author = author;
  }

  public News description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public News imageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
    return this;
  }

   /**
   * Get imageUrl
   * @return imageUrl
  **/
  @Schema(description = "")
  public String getImageUrl() {
    return imageUrl;
  }

  public void setImageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
  }

  public News keywords(List<String> keywords) {
    this.keywords = keywords;
    return this;
  }

  public News addKeywordsItem(String keywordsItem) {
    if (this.keywords == null) {
      this.keywords = new ArrayList<String>();
    }
    this.keywords.add(keywordsItem);
    return this;
  }

   /**
   * Get keywords
   * @return keywords
  **/
  @Schema(description = "")
  public List<String> getKeywords() {
    return keywords;
  }

  public void setKeywords(List<String> keywords) {
    this.keywords = keywords;
  }

  public News financialAssets(List<String> financialAssets) {
    this.financialAssets = financialAssets;
    return this;
  }

  public News addFinancialAssetsItem(String financialAssetsItem) {
    if (this.financialAssets == null) {
      this.financialAssets = new ArrayList<String>();
    }
    this.financialAssets.add(financialAssetsItem);
    return this;
  }

   /**
   * Get financialAssets
   * @return financialAssets
  **/
  @Schema(description = "")
  public List<String> getFinancialAssets() {
    return financialAssets;
  }

  public void setFinancialAssets(List<String> financialAssets) {
    this.financialAssets = financialAssets;
  }

  public News publishedTime(OffsetDateTime publishedTime) {
    this.publishedTime = publishedTime;
    return this;
  }

   /**
   * Get publishedTime
   * @return publishedTime
  **/
  @Schema(description = "")
  public OffsetDateTime getPublishedTime() {
    return publishedTime;
  }

  public void setPublishedTime(OffsetDateTime publishedTime) {
    this.publishedTime = publishedTime;
  }

  public News publisherName(String publisherName) {
    this.publisherName = publisherName;
    return this;
  }

   /**
   * Get publisherName
   * @return publisherName
  **/
  @Schema(description = "")
  public String getPublisherName() {
    return publisherName;
  }

  public void setPublisherName(String publisherName) {
    this.publisherName = publisherName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    News news = (News) o;
    return Objects.equals(this.title, news.title) &&
        Objects.equals(this.ampUrl, news.ampUrl) &&
        Objects.equals(this.articleUrl, news.articleUrl) &&
        Objects.equals(this.author, news.author) &&
        Objects.equals(this.description, news.description) &&
        Objects.equals(this.imageUrl, news.imageUrl) &&
        Objects.equals(this.keywords, news.keywords) &&
        Objects.equals(this.financialAssets, news.financialAssets) &&
        Objects.equals(this.publishedTime, news.publishedTime) &&
        Objects.equals(this.publisherName, news.publisherName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, ampUrl, articleUrl, author, description, imageUrl, keywords, financialAssets, publishedTime, publisherName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class News {\n");
    
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    ampUrl: ").append(toIndentedString(ampUrl)).append("\n");
    sb.append("    articleUrl: ").append(toIndentedString(articleUrl)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    imageUrl: ").append(toIndentedString(imageUrl)).append("\n");
    sb.append("    keywords: ").append(toIndentedString(keywords)).append("\n");
    sb.append("    financialAssets: ").append(toIndentedString(financialAssets)).append("\n");
    sb.append("    publishedTime: ").append(toIndentedString(publishedTime)).append("\n");
    sb.append("    publisherName: ").append(toIndentedString(publisherName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
