/*
 * Stocks
 * <h3>Authentication</h3>                     You need to authenticate to use this API.                     To authenticate click on the \"Authorize\" button and do one of the following steps.<br />                     1. Send your API key in the headers of the request by typing \"Bearer my-key\" on the Bearer authorization scheme.<br />                     2. Send your API key on the \"ApiKey\" query string parameter. To do this type your API key in the Query String authorization scheme.<br />                     Both methods are equally valid. We offer both options so that you can use the method that is easier to use in your application.<br />                     <br />                     <h3>API limits</h3>                     Your API key may be subject to daily/hourly limits. To know how much requests you have left look at the following headers in the response.<br />                     1. <strong>x-ratelimit-limit</strong> - The total number of requests that you are allowed to make in a given period (hour/day)                       2. <strong>x-ratelimit-remaining</strong> - The number of remaining requests that you can perform in the current period.<br />                     3. <strong>x-ratelimit-reset</strong> - The number of seconds until the current period resets.<br />                     <br />                     <h3>Suggestions</h3>                     You don't need to implement the whole API by hand in your programming language of choice.<br />                     Since this API has an OpenAPI specification you can use                      <a href=\"https://github.com/swagger-api/swagger-codegen\" target=\"_blank\">Swagger Generator</a>                      to automatically generate client stubs for more than 30 programming languages.                     <br />                     <br />                     You don't have an API key? <a href=\"https://www.equibles.com/api/pricing\" target=\"_blank\">Get one for free here.</a>
 *
 * OpenAPI spec version: v1
 * Contact: equibles@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.equibles.stocks.api;

import com.equibles.stocks.models.CurrenciesResponse;
import com.equibles.stocks.models.ExchangesResponse;
import com.equibles.stocks.models.FinancialAssetsResponse;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ExchangesApi
 */
@Ignore
public class ExchangesApiTest {

    private final ExchangesApi api = new ExchangesApi();

    /**
     * Get the list of all the currencies supported by this API.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void currenciesTest() throws Exception {
        CurrenciesResponse response = api.currencies();

        // TODO: test validations
    }
    /**
     * Get the list of all the exchanges supported by this API.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void listTest() throws Exception {
        ExchangesResponse response = api.list();

        // TODO: test validations
    }
    /**
     * Get all the stocks for a given exchange.
     *
     * Returns a list of fully qualified ticker names. A fully qualified ticker has the following structure: [Ticker].[ExchangeMic] Example: AAPL.XNAS.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void stocksTest() throws Exception {
        String operatingMic = null;
        FinancialAssetsResponse response = api.stocks(operatingMic);

        // TODO: test validations
    }
}
